GET http://localhost:3000/todos HTTP/1.1

###

POST http://localhost:3000/todo/new
Content-Type: application/json

{
    "text" : "Read book"
}

###

DELETE http://localhost:3000/todo/delete/63ea613b8317a5309303e9b7

###

GET  http://localhost:3000/todo/complete/63e0fb83494d77e8abf29409

###
PUT http://localhost:3000/todo/update/60e585d86177f95ff0574323
Content-Type: application/json

{
	"text": "Go Shopping for Milk"
}