GET http://localhost:3000/todos

###

POST http://localhost:3000/todo/new
Content-Type: application/json

{
    "text" : "Clean the room"
}

###

DELETE http://localhost:3000/todo/delete/63d688d14298d044b315e73c

###

PUT http://localhost:3000/todo/complete/63d688944298d044b315e73a